updated readme file
joans/teachme pull request #23
Opened 2022-07-18 20:14 UTC by SvenjaP3sto

- updated the readme file to incorporate some formatting, such as headings
- included launch.json in .gitignore

2022-07-19 05:30 UTC, joans commented
Hallo, die Readme Datei ist gar nicht im Commit enthalten?!

2022-07-22 18:23 UTC, SvenjaP3sto commented
next trial to add readme

2022-07-22 20:18 UTC, joans requested changes
Vielleicht solltest du dir mal einen Markdown-Previewer zu Gemüte führen, das macht das Schreiben von Markdown deutlich einfacher. Zum Beispiel [diesen hier](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) für VSCode.

2022-07-22 20:18 UTC, joans commented on readme.md
> +#TeachMe
Nach der Raute muss ein Leerzeichen kommen, sonst wird das nicht als Überschrift gesetzt.

2022-07-22 20:18 UTC, joans commented on readme.md
> +##Motivation
Hier auch Leerzeichen nach der Doppelraute

2022-07-22 20:18 UTC, joans commented on readme.md
> +We believe that anyone is brilliant in something and has an intrinsic motivation to share their expertise with others. Your signature dish is the yummiest bowl you have ever eaten and you want to tea
``` which just won\\'92t sound right ```
Du kannst das Apostroph ganz normal setzen, ohne das irgendwie zu escapen.

2022-07-22 20:18 UTC, joans commented on readme.md
> +TeachMe is currently being developed as a group project in the frame of the Web Development track of TechLabs Hamburg's Digital Shaper program. For more information on the program, visit [TechLabs HH
```[TechLabs HH] (https://techlabs.org/location/hamburg)```
Zwischen den beiden Klammerbegriffen darf kein Leerzeichen stehen, sonst wird der Link nicht korrekt gesetzt. Die beiden Klammern bilden quasi eine logische Einheit.

2022-07-22 20:18 UTC, joans commented on readme.md
> +Here is a [work-in-progress live demo] (https://joans.github.io/teachme/).
Hier auch noch das Leerzeichen entfernen…

2022-07-22 20:18 UTC, joans commented on readme.md
> +Backend: @NillemitBrille, @LHMoritz
Kannst mich auch bei Backend eintragen. 😃

2022-07-22 20:53 UTC, joans approved these changes, later dismissed
Sieht gut aus!

2022-07-22 20:55 UTC, joans commented
Kannst den Branch gerne mergen, wenn du magst!

2022-07-22 21:07 UTC, joans approved these changes
Sieht immer noch gut aus. Kannst immer noch mergen.

2022-07-22 21:09 UTC, merged