Feature/search function
joans/teachme pull request #24
Opened 2022-07-21 20:43 UTC by joans

Create Search Function in Back End and Front End and Render Search Results in own Page.

2022-07-22 06:19 UTC, LHMoritz commented
Lgtm was den Backenedpart angeht  👍

2022-07-22 18:27 UTC, SvenjaP3sto reviewed
How exactly does this work? Do we only allow specific search terms for the moment or how do we link these to results, i.e. profiles, categories, offers?

2022-07-22 18:51 UTC, lisa1ynn requested changes

2022-07-22 18:51 UTC, lisa1ynn commented on frontend/src/Pages/SearchResults.jsx
> +  const regularOutput = () => {};
Ist das ein Placeholder für später?

2022-07-22 18:51 UTC, lisa1ynn commented on frontend/src/Pages/SearchResults.jsx
> +        There {searchResults.count !== 1 ? "were" : "was"} {searchResults.count}{" "}
Es sollte auch einen Case geben, wenn es keine Ergebnisse gibt. `searchResults.count !== 1` -> Auch wenn es keine, also "0" Ergebnisse gibt, wird "were" verwendet und es wird keine Zahl angezeigt:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/76967309/180502414-f2577f94-feed-455b-871b-1482288d6a71.png">

2022-07-22 20:01 UTC, joans commented on frontend/src/Pages/SearchResults.jsx
> +        There {searchResults.count !== 1 ? "were" : "was"} {searchResults.count}{" "}
Hallo Lisa, dass keine Zahl erscheint liegt am Network Error, also daran, dass du keine Verbindung zur Datenbank hast, also kein Backend laufen hast bzw. keine Datenbank initialisiert hast! Ich hab den State für die Suchergebnisse jetzt mit 0 initiiert. Danke für den Hinweis, jetzt sollte es also passen. Aber grammatikalisch ergibt "there were 0 results" doch Sinn, oder nicht? Was würdest du denn schreiben? "There was 0 results"?

2022-07-22 20:02 UTC, joans commented on frontend/src/Pages/SearchResults.jsx
> +  const regularOutput = () => {};
Ja ist Quatsch. Habe ich rausgenommen.

2022-07-22 20:03 UTC, joans commented
> How exactly does this work? Do we only allow specific search terms for the moment or how do we link these to results, i.e. profiles, categories, offers?

No, the search works by returning offers that match either in title or in the text of the offer. The returned offer cards have links to the full offer text and those full offer texts have links to the profile pages... We can always change this behavior if this is not what we want!

2022-07-22 20:39 UTC, lisa1ynn commented on frontend/src/Pages/SearchResults.jsx
> +        There {searchResults.count !== 1 ? "were" : "was"} {searchResults.count}{" "}
Jaa, sorry. "There were 0 results" macht natürlich Sinn. 👍🏼

2022-07-23 10:52 UTC, joans commented on frontend/src/Pages/SearchResults.jsx
> +        There {searchResults.count !== 1 ? "were" : "was"} {searchResults.count}{" "}
Ok, ich glaube dann habe ich deine Punkte alle adressiert, oder? Kannst du den letzten Commit noch reviewen und Bescheid geben, ob es jetzt passt?

2022-07-24 14:52 UTC, lisa1ynn approved these changes
Sieht gut aus. 
Man könnte den Header noch auf mobile/ responsive optimieren. Aber dazu würde ich einen neuen Branch erstellen. 
<img width="198" alt="image" src="https://user-images.githubusercontent.com/76967309/180652728-38cb0db6-1c9e-4eee-9eb5-0cf73815f7c3.png">

2022-07-24 17:23 UTC, joans commented
> Man könnte den Header noch auf mobile/ responsive optimieren. Aber dazu würde ich einen neuen Branch erstellen. 

Danke, ja wird gemacht!

2022-07-24 20:02 UTC, merged