Layout copyright
joans/teachme pull request #28
Opened 2022-08-01 20:53 UTC by SvenjaP3sto

implemented copyright notice

2022-08-02 05:47 UTC, joans requested changes
Habe hier noch einige Fragen bzw. Anregungen.

2022-08-02 05:47 UTC, joans commented on frontend/src/App.jsx
> +import Copyright from "./Layout/Copyright";
Die Datei "Layout.jsx" ist nicht in den Commits enthalten. Kannst du die noch hinzufügen? Gibt es einen Grund, warum die Datei so spezifisch "Copyright" heißt, und nicht "Footer" oder so? Also sind wir uns sicher, dass da immer nur ein Copyright drinstehen wird?

2022-08-02 05:47 UTC, joans commented on frontend/src/Pages/PostDetail.jsx
> +              src="https://autorhodes.com/sites/default/files/special-offer_4.jpg"
Vielleicht lieber eine Grafik verwenden, die unter einer offenen Lizenz steht (zum Beispiel Creative Commons), siehe z.B. https://unsplash.com

2022-08-02 05:47 UTC, joans commented on frontend/src/Pages/PostDetail.jsx
> +          <Link to={`/post/${singlePost.updatedAt}`}>
Die Seite "/post/${singlePost.updatedAt}" existiert nicht. Der Link wird aktuell ins Leere führen.

Wir haben auch aktuell keine Möglichkeit, so eine Seite zu implementieren. Es kann immer nur eine "ID" entgegen genommen werden pro Seite. Aktuell ist das bei uns die UUID des Posts, die die Seite "Post" entgegen nehmen kann.

2022-08-02 05:47 UTC, joans commented on frontend/src/Pages/PostDetail.jsx
> +          {/* How do I format date information from database? */}
Hat nichts mit der Database zu tun. Schau mal zum Beispiel hier: https://www.w3docs.com/snippets/javascript/how-to-format-a-javascript-date.html

2022-08-02 05:47 UTC, joans commented on frontend/src/Pages/PostDetails.module.css
> +}
Bitte diese globalen Variablen auch global definiert lassen (also in der app.css) und hier entfernen, sonst haben wir bald keinen Überblick, wo diese Variablen überall definiert sind.

Warum willst du diese Variablen hier überhaupt noch mal definieren? Die Variablen kannst du ohne Probleme auch einfach so verwenden, ohne sie hier erneut zu definieren.

Will sagen: wenn du den Code hier entfernst wird alles genau so funktionieren wie mit diesem Code.

2022-08-02 05:47 UTC, joans commented on frontend/src/Pages/PostDetails.module.css
> +h1 {
Funktioniert das? Sollte eigentlich nicht funktionieren. Eigentlich brauchst du bei CSS Modules immer einen ClassName, den du definierst, also in deinem Fall von mir aus ".title", den du dann natürlich auch in der "PostDetail.jsx" dem entsprechenden Element anhängst.

2022-08-07 14:24 UTC, joans commented on frontend/src/Pages/PostDetail.jsx
> +            <img src="https://unsplash.com/photos/GI1hwOGqGtE" alt="test" />
Wird so nicht funktionieren, weil kein Bild dahinter liegt, sondern eine Website.

2022-08-07 14:26 UTC, joans commented on frontend/src/Pages/PostDetail.jsx
> +          <Link to={`/user/${singlePost.updatedAt}`}>
Immer noch mit dem Link? Der Link funktioniert so nicht, wie bereits besprochen.

2022-08-11 20:11 UTC, joans requested changes

2022-08-11 20:11 UTC, joans commented on frontend/src/App.css
> +}
Warum hast du das direkt in der App.css hinzugefügt? Bitte in die Footer.module.css einfügen. In der App.css sollten nur **globale** Werte aufgelistet werden.

2022-08-11 20:11 UTC, joans commented on frontend/src/Layout/Footer.jsx
> +      <Grid container spacing={2} className={classes.footer_nav}>
Ich checke nicht, wieso du hier MUI Grid nutzt und nicht einfach CSS Grid. Was ist der Vorteil?

2022-08-11 20:11 UTC, joans commented on frontend/package.json
> +    "@fortawesome/react-fontawesome": "^0.2.0",
Warum diese drei Pakete? Werden auch nicht mehr in deinem Code referenziert. Bitte ungenutzte Imports wieder entfernen.

2022-08-11 20:11 UTC, joans commented on frontend/src/Layout/Footer.jsx
> +      <Grid container spacing={2} className={classes.footer_nav}>
Das Grid funktioniert bei mir nicht. Ich hab dir ja schon im Chat geschrieben diesbezüglich. Du brauchst eigentlich auch gar kein Grid in dieser Komponente.

2022-08-11 20:11 UTC, joans commented on frontend/src/Pages/PostDetail.jsx
> +          <Moment format="DD/MM/YYYY, HH:mm:ss">{singlePost.updatedAt}</Moment>
Wie im Chat geschrieben brauchst du kein Moment, sondern einfach nur folgende Funktion:

``` 
const formatDate = (date) => {
    let dt = new Date(date);
    const DeFormatter = new Intl.DateTimeFormat("en-GB", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "numeric",
    });
    return DeFormatter.format(dt);
  }; 
```

Und dann hier an dieser Stelle mit 
`<p>Last updated on: {formatDate(singlePost.updatedAt)}</p>`
aufrufen.

2022-08-17 07:21 UTC, joans commented on frontend/package.json
> +    "@fortawesome/react-fontawesome": "^0.2.0",
Ach so und bitte dafür

npm remove _paketname-hier-einfügen_ 

nutzen

2022-08-22 16:16 UTC, SvenjaP3sto commented
Footer was implemented in another branch fix/layout_copyright

2022-08-22 16:16 UTC, closed without merging