Feature/edit feature frontend
joans/teachme pull request #32
Opened 2022-08-17 19:51 UTC by LHMoritz

2022-08-17 19:55 UTC, joans commented
Wieso ist der Titel des PR "Edit Feature **Frontend**"? Ich sehe nur eine Anpassung des Backends.

2022-08-17 20:45 UTC, LHMoritz commented
Gute Frage, ich glaube das war ausversehen

2022-08-17 21:30 UTC, joans requested changes
Schau dir die Update Post Route noch mal an. Du solltest die User UUID aus dem JWT Token verwenden, also `req.userId`

2022-08-17 21:30 UTC, joans commented on backend/app.js
> +app.delete("/delete_post/:postuuid/:useruuid", authJwt.verifyToken, async (req, res) => {
Du musst doch nur die Post uuid abfragen. Die User uuid kommt doch aus dem JWT Token

2022-08-17 21:30 UTC, joans commented on backend/app.js
> +  const useruuid = req.params.useruuid;
Hier müsste es `req.userId` statt `req.params.useruuid` heißen, damit du den JWT Token auswertest und nicht das was im Frontend eingegeben wird.

2022-08-17 21:30 UTC, joans commented on backend/app.js
> +app.get("/userLite/:uuid", async (req, res) => {
Case-Sensitivity in der url ist ein großes no-no aus meiner Sicht. Besser alles klein schreiben.

2022-08-17 21:30 UTC, joans commented on backend/app.js
> +      where: { uuid: userUUID },
Nee. Du musst auch hier den User aus dem JWT Token verwenden. Also `req.userId` statt `userUUID`.

2022-08-17 21:30 UTC, joans commented on backend/app.js
> +    if (dbUser.uuid === req.userId) {
Brauchst du hier nicht unbedingt. Du holst dir ja schon vorher genau den JWT User aus der db.

2022-08-17 21:30 UTC, joans commented on backend/app.js
> +      return res.json(dbUser);
Aufpassen. Was wird hier returned? Hoffentlich nicht das pw

2022-08-20 16:58 UTC, joans commented on backend/app.js
> +      return res.json(dbUser);
Nein, macht er nicht. Gerade gecheckt.

2022-08-22 18:49 UTC, LHMoritz commented on backend/app.js
> +      return res.json(dbUser);
Jo habe das auch ausprobiert weil ich mir nicht sicher war 😆

2022-08-22 18:49 UTC, LHMoritz commented on backend/app.js
> +    if (dbUser.uuid === req.userId) {
Habe ich mal rausgenommen

2022-08-22 19:46 UTC, joans approved these changes
passt

2022-08-22 19:46 UTC, merged